version: "3"

services:
  frontend:
    image: 658381509424.dkr.ecr.ap-northeast-1.amazonaws.com/arput/frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: 'npm run dev'
    depends_on:
      - backend

  backend:
    image: 658381509424.dkr.ecr.ap-northeast-1.amazonaws.com/arput/backend:latest
    build:
      context: ./backend
    ports:
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/arput"
      ARPUT_ES_HOST: "es"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      interval: 30s
      retries: 10
      start_period: 40s

volumes:
  db-data:
  node_modules:
  esdata:
    driver: local
