version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: 'npm run dev'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/arput"
      ARPUT_ES_HOST: "es"
    depends_on:
      db:
        condition: service_healthy
      es:
        condition: service_healthy

  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      interval: 30s
      retries: 10
      start_period: 40s

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    depends_on:
      - swagger-api
    

  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml

  es:
    build:
      context: elasticsearch
    container_name: es
    environment:
      discovery.type: single-node
      cluster.name: docker-cluster
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      http.cors.allow-origin: '*'
      http.cors.enabled: 'true'
      xpack.security.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://es:9200/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  db-data:
  node_modules:
  esdata:
    driver: local
