version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5050:8080"
    depends_on:
      - db
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  db-data:
