name: docker-build
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  app-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build app
        run: docker-compose build backend
      - name: compose up app
        run: docker-compose up -d backend
